### ISSUE TITLE
Eq Void instance

### ISSUE THREAD

**Issue by bergmark** [silkapp/rest#109]
No biggie, but we forgot to add this before the release. @hesselink did you figure out what instance you liked best? :)

**Comment by hesselink** [comment]
I think something like this is fine:

```
instance Eq Void where
  x == _ = magic x
```

Saying `True` or `False` seems weird to me, since you'd be giving a result for comparing two bottoms. After that we'd have to make a choice about laziness (i.e. is `(undefined ==) :: Void -> Bool` already bottom, or can you first apply it to another bottom?). I'd say only the resulting `Bool` should be bottom. Then we'd have to choose which one. We can't choose both, so the first one is as good as any, I guess.

I've just pushed this, as well as instances for `Ord` (similar) and `Read` (always failing) to [void-instances](https://github.com/silkapp/rest/compare/void-instances). Any more we should add?

**Comment by bergmark** [comment]
`Eq` is the only one I've needed so far.

I also forgot, was there a reason we don't use the `void` package?

**Comment by hesselink** [comment]
We didn't want to pull in the dependencies for such a simple data type, especially since we didn't really do much with it initially. Now that we're adding more functionality, we could switch, although it doesn't matter much: nobody's going to interface between different `Void` types, I guess. Also (very minor): I like our representation better. :)

**Comment by hesselink** [comment]
Shall I merge this?

**Comment by bergmark** [comment]
Do it!

**Comment by hesselink** [comment]
Committed as 4baa3de117822805c3937806ad54552208cdc8ab, will release as rest-types-1.13.1.
