### ISSUE TITLE
Auth?

### ISSUE THREAD

**Issue by twopoint718** [silkapp/rest#80]
Is there an auth system for rest? Or is there any plan to implement this?

**Comment by nd2s** [comment]
Has there been any progress on this? Or are there maybe some examples how authentication/authorisation could be implemented elegantly? I'm not quite sure how to implement even a very basic auth system.

**Comment by hesselink** [comment]
No, we haven't done any work on this, and I suspect we won't any time soon. The system I described above is relatively easy to implement. On the top level (so not in rest) you would handle authentication, and then you can pass the user (or user id) into the state for your handlers. Then each handler can check the authorization for the current user. The rest-example does the latter part, although it doesn't do authentication (the user is just passed in the request).

**Comment by nd2s** [comment]
Thanks for your reply, but I'm not quite sure I understand how I can pass state into the handlers.

Are you talking about doing database lookups in some WAI middleware and then adding some headers to the request for example?

This sounds a bit ugly because I'd need to add all user information into the HTTP headers instead of just passing some `User` type. Although I'd probably only need id and some role in most cases...
